# Aula 4 - Desafío: ¡Vamos a practicar!

Realizar análisis utilizando archivo CSV: alumnos.csv.



---

In [ ]:
import pandas as pd
#url = 'https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv'
url = 'https://gist.githubusercontent.com/BibiTC/63f71c45d41f4a5319f73f717b9362de/raw/061a3f6fcef9173196569b6b05742797e31a45eb/alumnos.csv'
df = pd.read_csv(url)

In [ ]:
df.shape

(18, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nombre         18 non-null     object
 1   Edad           18 non-null     int64
 2   Nota           12 non-null     float64
 3   Aprobado       18 non-null     object
 4   Puntos_extras  12 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 852.0+ bytes

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head()

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True

## 1. Los estudiantes participaron en una actividad extracurricular y ganaron puntos extras. Estos puntos extras corresponden al 40% de su nota actual. Por lo tanto, crea una columna llamada "Puntos_extras" que contenga los puntos extras de cada estudiante, es decir, el 40% de su nota actual.

In [ ]:
df['Puntos_extras'] = df['Nota'] * 0.40
#datos['Puntos_extras'] = datos['Nota'].apply(lambda x: x*0.4)

In [ ]:
df.head()

    Nombre  Edad  Nota Aprobado  Puntos_extras
0  Alberto    20   7.5     True            3.0
1      Ana    18   NaN    False            NaN
2   Camila    27   2.5    False            1.0
3    David    18   5.0    False            2.0
4    Brian    21  10.0     True            4.0

## 2. Crea otra columna llamada "Notas_finales" que contenga las notas de cada estudiante sumadas con los puntos extras.

In [ ]:
df['Notas_finales'] = df['Nota'] + df['Puntos_extras']

In [ ]:
df.tail()

    Nombre  Edad  Nota   Aprobado  Puntos_extras  Notas_finales
13  Miriam    25   9.0       True            3.6           12.6
14   Pablo    37   NaN      False            NaN            NaN
15  Milena    29   7.0       True            2.8            9.8
16   Lucas    33   NaN      False            NaN            NaN
17   Nadia    34   8.0  Verdadero            3.2           11.2

## 3. Dado que hubo una puntuación extra, algunos estudiantes que no habían sido aprobados antes pueden haber sido aprobados ahora. En función de esto, crea una columna llamada "Aprobado_final" con los siguientes valores:

True: si el estudiante está aprobado (la nota final debe ser mayor o igual a 7.0).
False: si el estudiante está reprobado (la nota final debe ser menor que 7.0).

In [ ]:
df['aprobado_final'] = df['Notas_finales'].apply(lambda x: True if x >=7 else False)

In [ ]:
df.head()

    Nombre  Edad  Nota Aprobado  Puntos_extras  Notas_finales  aprobado_final
0  Alberto    20   7.5     True            3.0           10.5            True
1      Ana    18   NaN    False            NaN            NaN           False
2   Camila    27   2.5    False            1.0            3.5           False
3    David    18   5.0    False            2.0            7.0            True
4    Brian    21  10.0     True            4.0           14.0            True

In [ ]:
#df = df.drop('aporbado_final', axis=1)
#display(df.head())

    Nombre  Edad  Nota Aprobado  Puntos_extras  Notas_finales  aprobado_final
0  Alberto    20   7.5     True            3.0           10.5            True
1      Ana    18   NaN    False            NaN            NaN           False
2   Camila    27   2.5    False            1.0            3.5           False
3    David    18   5.0    False            2.0            7.0           False
4    Brian    21  10.0     True            4.0           14.0            True

In [ ]:
df

,Nombre,Edad,Nota,Aprobado,Puntos_extras,Notas_finales,aprobado_final
0,Alberto,20,7.5,True,3.00,10.50,True
1,Ana,18,NaN,False,NaN,NaN,False
2,Camila,27,2.5,False,1.00,3.50,False
3,David,18,5.0,False,2.00,7.00,True
4,Brian,21,10.0,True,4.00,14.00,True
5,Bruna,23,NaN,False,NaN,NaN,False
6,Daniela,21,7.0,True,2.80,9.80,True
7,Carlos,19,6.0,False,2.40,8.40,True
8,Alicia,35,5.6,False,2.24,7.84,True
9,Victor,28,NaN,False,NaN,NaN,False
10,Danilo,21,NaN,False,NaN,NaN,False
11,Ignacio,24,4.5,False,1.80,6.30,False
12,Stephany,26,10.0,True,4.00,14.00,True
13,Miriam,25,9.0,True,3.60,12.60,True
14,Pablo,37,NaN,False,NaN,NaN,False
15,Milena,29,7.0,True,2.80,9.80,True
16,Lucas,33,NaN,False,NaN,NaN,False
17,Nadia,34,8.0,Verdadero,3.20,11.20,True

## 4. Realiza una selección y verifica qué estudiantes no habían sido aprobados anteriormente, pero ahora fueron aprobados después de sumar los puntos extras.

In [ ]:
aprobaron_por_puntos_extras =  (df['Aprobado'] == 'False')  & (df['aprobado_final'] == True)
#datos.query('Aprobado == False & Aprobado_final == True')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Nombre          18 non-null     object
 1   Edad            18 non-null     int64
 2   Nota            12 non-null     float64
 3   Aprobado        18 non-null     object
 4   Puntos_extras   12 non-null     float64
 5   Notas_finales   12 non-null     float64
 6   aprobado_final  18 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1014.0+ bytes

In [ ]:
aprobaron_por_puntos_extras

   Nombre  Edad  Nota Aprobado  Puntos_extras  Notas_finales  aprobado_final
3   David    18   5.0    False           2.00           7.00            True
7  Carlos    19   6.0    False           2.40           8.40            True
8  Alicia    35   5.6    False           2.24           7.84            True

In [ ]:
df[aprobaron_por_puntos_extras]

   Nombre  Edad  Nota Aprobado  Puntos_extras  Notas_finales  aprobado_final
3   David    18   5.0    False           2.00           7.00            True
7  Carlos    19   6.0    False           2.40           8.40            True
8  Alicia    35   5.6    False           2.24           7.84            True