# Desafío: ¡Vamos a practicar!

Realizar análisis utilizando archivo CSV: alumnos.csv.



---



1. Importa el archivo alumnos.csv y almacena su contenido en un DataFrame de Pandas.

In [ ]:
import pandas as pd
url = 'https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv'
datos = pd.read_csv(url)

In [ ]:
datos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

In [ ]:
type(datos)

pandas.core.frame.DataFrame

2. Visualiza las primeras 7 filas del DataFrame y las últimas 5.

In [ ]:
datos.head(7)

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True
5    Bruna    23   NaN    False
6  Daniela    21   7.0     True

In [ ]:
datos.tail()

    Nombre  Edad  Nota   Aprobado
13  Miriam    25   9.0       True
14   Pablo    37   NaN      False
15  Milena    29   7.0       True
16   Lucas    33   NaN      False
17   Nadia    34   8.0  Verdadero

3. Verifica la cantidad de filas y columnas en este DataFrame.

In [ ]:
datos.shape

(18, 4)

4. Explora las columnas del DataFrame y analiza los tipos de datos presentes en cada columna.

In [ ]:
datos.columns

Index(['Nombre', 'Edad', 'Nota', 'Aprobado'], dtype='object')

In [ ]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    18 non-null     object
 1   Edad      18 non-null     int64
 2   Nota      12 non-null     float64
 3   Aprobado  18 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 708.0+ bytes

In [ ]:
# Seleccionar una columna
datos['Nombre']

# Seleccionar múltiples columnas
datos[['Nombre', 'Edad']]
datos[['Nombre', 'Edad','Nota','Aprobado']]

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

In [ ]:
# Verificar los tipos de datos en cada columna
datos.dtypes

Nombre       object
Edad          int64
Nota        float64
Aprobado     object
dtype: object

Extra: Calcula algunas estadísticas descriptivas básicas de los datos en el DataFrame (media, desviación estándar, etc.). Pista: busca el método "describe".

In [ ]:
datos.describe()

            Edad       Nota
count  18.000000  12.000000
mean   25.500000   6.841667
std     6.070662   2.264532
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000

El método describe() es una de las funciones más útiles de Pandas para el análisis exploratorio de datos. Se utiliza para calcular algunas estadísticas descriptivas básicas de los datos en un DataFrame o en una columna específica de un DataFrame.

#Aula 3

## 1- Verifica si la base de datos contiene datos nulos y, en caso de tenerlos, realiza el tratamiento de estos datos nulos de la manera que consideres más coherente con la situación.

In [ ]:
datos.isnull()

    Nombre   Edad   Nota  Aprobado
0    False  False  False     False
1    False  False   True     False
2    False  False  False     False
3    False  False  False     False
4    False  False  False     False
5    False  False   True     False
6    False  False  False     False
7    False  False  False     False
8    False  False  False     False
9    False  False   True     False
10   False  False   True     False
11   False  False  False     False
12   False  False  False     False
13   False  False  False     False
14   False  False   True     False
15   False  False  False     False
16   False  False   True     False
17   False  False  False     False

In [ ]:
# Devuelve cada columna con los nulos que tiene
datos.isnull().sum()

Nombre      0
Edad        0
Nota        6
Aprobado    0
dtype: int64

In [ ]:
# Llena todos los valores nulos con 0
datos.fillna(0)

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   0.0      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   0.0      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   0.0      False
10    Danilo    21   0.0      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   0.0      False
15    Milena    29   7.0       True
16     Lucas    33   0.0      False
17     Nadia    34   8.0  Verdadero

In [ ]:
datos = datos.fillna(0)
datos.isnull().sum()

Nombre      0
Edad        0
Nota        0
Aprobado    0
dtype: int64

## 2-Los estudiantes "Alicia" y "Carlos" ya no forman parte del grupo. Por lo tanto, elimínalos de la base de datos.

In [ ]:
datos.query('Nombre in ["Alicia","Carlos"]')

   Nombre  Edad  Nota Aprobado
7  Carlos    19   6.0    False
8  Alicia    35   5.6    False

In [ ]:
datos.drop(datos.query('Nombre in ["Alicia","Carlos"]').index, inplace=True)

In [ ]:
datos.query('Nombre in ["Alicia","Carlos"]')

Empty DataFrame
Columns: [Nombre, Edad, Nota, Aprobado]
Index: []

In [ ]:
datos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   0.0      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   0.0      False
6    Daniela    21   7.0       True
9     Victor    28   0.0      False
10    Danilo    21   0.0      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   0.0      False
15    Milena    29   7.0       True
16     Lucas    33   0.0      False
17     Nadia    34   8.0  Verdadero

## 3- Aplica un filtro que seleccione solo a los estudiantes que fueron aprobados.

In [ ]:
datos['Aprobado'] == 1

0     False
1     False
2     False
3     False
4     False
5     False
6     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
Name: Aprobado, dtype: bool

In [ ]:
filtro1

0     False
1     False
2     False
3     False
4     False
5     False
6     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
Name: Aprobado, dtype: bool

In [ ]:
type(filtro1)

pandas.core.series.Series

In [ ]:
datos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   0.0      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   0.0      False
6    Daniela    21   7.0       True
9     Victor    28   0.0      False
10    Danilo    21   0.0      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   0.0      False
15    Milena    29   7.0       True
16     Lucas    33   0.0      False
17     Nadia    34   8.0  Verdadero

In [ ]:
filtro1 = datos[(datos['Aprobado'] == 'True') | (datos['Aprobado'] == 'Verdadero')]

In [ ]:
filtro1

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
4      Brian    21  10.0       True
6    Daniela    21   7.0       True
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
15    Milena    29   7.0       True
17     Nadia    34   8.0  Verdadero

In [ ]:
filtro1 = (datos['Aprobado'] == 'True') | (datos['Aprobado'] == 'Verdadero')

In [ ]:
filtro1

0      True
1     False
2     False
3     False
4      True
5     False
6      True
9     False
10    False
11    False
12     True
13     True
14    False
15     True
16    False
17    False
Name: Aprobado, dtype: bool

In [ ]:
df_estudiantes_aprobados = datos[filtro1]

In [ ]:
df_estudiantes_aprobados

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
4      Brian    21  10.0       True
6    Daniela    21   7.0       True
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
15    Milena    29   7.0       True
17     Nadia    34   8.0  Verdadero

## 4- Guarda el DataFrame que contiene solo a los estudiantes aprobados en un archivo CSV llamado "alumnos_aprobados.csv".|

In [ ]:
df_estudiantes_aprobados.to_csv('estudiantes_aprobados.csv')

## Extra: Al revisar las calificaciones de los estudiantes aprobados, notamos que algunas calificaciones eran incorrectas. Las estudiantes que obtuvieron una calificación de 7.0, en realidad tenían un punto extra que no se contabilizó. Por lo tanto, reemplaza las calificaciones de 7.0 en la base de datos por 8.0. Consejo: busca el método replace.

In [ ]:
df_estudiantes_aprobados

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
4      Brian    21  10.0       True
6    Daniela    21   7.0       True
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
15    Milena    29   7.0       True
17     Nadia    34   8.0  Verdadero

In [ ]:
df_estudiantes_aprobados.loc[:, 'Nota'] = df_estudiantes_aprobados['Nota'].replace(7.0, 8.0)

<ipython-input-70-3864437616>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_estudiantes_aprobados['Nota'] = df_estudiantes_aprobados['Nota'].replace(7.0, 8.0)

In [ ]:
df_estudiantes_aprobados['Nota'].replace(7.0, 8.0)

0      7.5
4     10.0
6      8.0
12    10.0
13     9.0
15     8.0
17     8.0
Name: Nota, dtype: float64

In [ ]:
df_estudiantes_aprobados

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
4      Brian    21  10.0       True
6    Daniela    21   8.0       True
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
15    Milena    29   8.0       True
17     Nadia    34   8.0  Verdadero