# **Pandas**

## **Imporando la base de datos**

In [1]:
import pandas as pd

# Base de datos
url = 'https://gist.githubusercontent.com/ahcamachod/a572cfcc2527046db93101f88011b26e/raw/ffb13f45a79d31223e645611a119397dd127ee3c/alquiler.csv'

pd.read_csv(url)

      Tipo;Colonia;Habitaciones;Garages;Suites;Area;Valor;Condominio;Impuesto
0          Cocineta;Condesa;1;0;0;40;5950.0;1750.0;210.0
1                       Casa;Polanco;2;0;1;100;24500.0;;
2      Conjunto Comercial/Sala;Santa Fe;0;4;0;150;182...
3      Departamento;Centro Histórico;1;0;0;15;2800.0;...
4          Departamento;Del Valle;1;0;0;48;2800.0;805.0;
...                                                  ...
25116  Cochera/Estacionamiento;Centro Histórico;0;0;0...
25117  Cocineta;Centro Histórico;0;0;0;27;2800.0;1225...
25118  Departamento;Mixcoac;2;1;0;48;4900.0;1781.5;129.5
25119  Departamento;Lomas de Chapultepec;2;0;0;70;105...
25120  Conjunto Comercial/Sala;Centro Histórico;0;0;0...

[25121 rows x 1 columns]

In [2]:
pd.read_csv(url,sep=';')

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [3]:
datos = pd.read_csv(url, sep =';')
datos

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [4]:
# visualizar mejor los datos
datos.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN

In [5]:
datos.tail()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [6]:
datos.head(10)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
5,Casa de Condominio,Santa Fe,5,4,5,750,77000.0,NaN,NaN
6,Conjunto Comercial/Sala,Centro Histórico,0,3,0,695,122500.0,67175.5,10605.0
7,Departamento,Centro Histórico,1,0,0,36,4200.0,NaN,NaN
8,Departamento,Condesa,1,0,1,40,7000.0,1963.5,175.0
9,Cocineta,Condesa,1,0,0,27,6300.0,1753.5,NaN

In [7]:
# Tomar una muestra de 10
datos.sample(10)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
12449,Casa,Villa Coapa,2,0,0,110,4900.0,NaN,NaN
11703,Departamento,Santa Fe,5,2,5,1200,84000.0,26250.0,19250.0
8696,Conjunto Comercial/Sala,Juárez,0,5,0,525,165375.0,45937.5,NaN
17271,Departamento en Hotel,Coyoacán,2,2,2,86,15050.0,6993.0,840.0
5307,Departamento,Santa Fe,2,2,1,100,17500.0,9975.0,2054.5
524,Departamento,Lomas de Chapultepec,2,3,1,168,31500.0,7434.0,1970.5
19989,Cocineta,Roma,1,0,0,22,4200.0,945.0,NaN
5675,Departamento,San Ángel,3,0,1,112,10500.0,3836.0,NaN
22973,Conjunto Comercial/Sala,Centro Histórico,0,1,0,47,5600.0,3325.0,280.0
14417,Departamento,Condesa,3,1,0,125,11550.0,4396.0,NaN

In [9]:
# Ver que tipo de dato es
type(datos)

pandas.core.frame.DataFrame

## **Exploración inicial de los datos**

In [11]:
datos.sample(5)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
18884,Departamento,Santa Fe,4,3,2,246,24500.0,7000.0,16800.0
7871,Departamento,Coyoacán,2,0,0,63,14000.0,2492.0,602.0
12488,Departamento,Coyoacán,4,2,3,380,104650.0,17500.0,NaN
24178,Departamento,Condesa,2,0,0,80,8750.0,2800.0,NaN
3629,Departamento,Santa Fe,2,1,1,84,8750.0,7297.5,927.5

In [12]:
#1. Saber el tamaño
datos.shape

(25121, 9)

In [14]:
datos.columns

Index(['Tipo', 'Colonia', 'Habitaciones', 'Garages', 'Suites', 'Area', 'Valor',
       'Condominio', 'Impuesto'],
      dtype='object')

In [17]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25121 entries, 0 to 25120
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tipo          25121 non-null  object
 1   Colonia       25121 non-null  object
 2   Habitaciones  25121 non-null  int64
 3   Garages       25121 non-null  int64
 4   Suites        25121 non-null  int64
 5   Area          25121 non-null  int64
 6   Valor         25107 non-null  float64
 7   Condominio    22495 non-null  float64
 8   Impuesto      18037 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.7+ MB

In [21]:
datos['Tipo']

0                       Cocineta
1                           Casa
2        Conjunto Comercial/Sala
3                   Departamento
4                   Departamento
                  ...
25116    Cochera/Estacionamiento
25117                   Cocineta
25118               Departamento
25119               Departamento
25120    Conjunto Comercial/Sala
Name: Tipo, Length: 25121, dtype: object

In [22]:
datos[['Habitaciones','Valor']]

       Habitaciones    Valor
0                 1   5950.0
1                 2  24500.0
2                 0  18200.0
3                 1   2800.0
4                 1   2800.0
...             ...      ...
25116             0  49000.0
25117             0   2800.0
25118             2   4900.0
25119             2  10500.0
25120             0  22750.0

[25121 rows x 2 columns]